- name: Setup web servers
  hosts: role_web
  become: yes
  roles:
    - docker

- name: Setup build servers
  hosts: role_build
  become: yes
  roles:
    - java
    - maven

- name: Setup db servers
  hosts: role_db
  become: yes
  roles:
    - maven 

- name: Setup cache servers
  hosts: role_cache
  become: yes
  roles:
    - java
