name: Provision and Configure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

  ansible:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible + Python venv
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-venv python3-pip

          python3 -m venv venv
          source venv/bin/activate

          pip install boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PIPELINE_KEYPAIR_PEM }}" > ~/.ssh/pipeline.pem
          chmod 600 ~/.ssh/pipeline.pem

      - name: Verify Dynamic Inventory
        run: |
          source venv/bin/activate
          ansible-inventory -i aws_ec2.yml --graph
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Wait for EC2 to be ready
        run: |
          source venv/bin/activate
          ansible all -i aws_ec2.yml -m wait_for_connection --timeout=300
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Run Ansible Playbook
        run: |
          source venv/bin/activate
          ansible-playbook -i aws_ec2.yml site1.yml \
            --private-key ~/.ssh/pipeline.pem
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          ANSIBLE_HOST_KEY_CHECKING: False
