name: Provision and Configure

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [ main ] # run on push to main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: .   # root directory

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .   # root directory
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1   # adjust to your region

  ansible:
    runs-on: self-hosted
    needs: terraform   # depends on Terraform job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible + boto3
        run: |
          sudo apt-get update && sudo apt-get install -y ansible python3-pip
          pip install boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PIPELINE_KEYPAIR_PEM }}" > ~/.ssh/pipeline.pem
          chmod 600 ~/.ssh/pipeline.pem

      - name: Verify Dynamic Inventory
        run: |
          ansible-inventory -i aws_ec2.yml --graph
          sleep 10
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      - name: Run Ansible Playbook
        run: ansible-playbook -i aws_ec2.yml site1.yml --private-key ~/.ssh/pipeline.pem
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          ANSIBLE_HOST_KEY_CHECKING: False

  destroy:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' # only manual runs
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: .   # root directory

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: .   # root directory
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
